### ISSUE TITLE
Timeout while waiting for UCS Blades to reboot

### ISSUE THREAD

**Issue by btpier** [oVirt/ovirt-ansible-cluster-upgrade#55]
When using this role and setting reboot_after_upgrade : true, the following exception occurs when using on Cisco UCS blades:

TASK [oVirt.cluster-upgrade : Upgrade host] 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: Error while waiting on result state of the entity.

The timeout var in the playbook is set to:  upgrade_timeout: 3600

The total time from the start of updating a particular host until the host is back "up" in oVirt is about 20-30 minutes and the hosts do activate without intervention. The role works as expect if reboot_after_upgrade is set to false.

**Comment by machacekondra** [comment]
We fail in following cases:
  1) host is in state `error`, `install_failed` or `non_operational`
  2) host is in state `non_responsive` longer then 1minute. 
  3) in event log there is message with id 65, 140, 166 or 17

I guess in your case it's because of 2). What's your value of engine-config option `ServerRebootTimeout`? I guess it's low, so the host is in REBOOT state only for few minutes and then it for like 20minutes in `non_responsive` state, is that correct?

**Comment by btpier** [comment]
Yes! You are correct. Our ServerRebootTimeout is only 300 seconds.  I'll adjust that to 15 minutes and do some testing.  I was trying to track this down for a while before creating an issue and couldn't find  another timeout value that I knew had to exist somewhere. I don't recall ever seeing reference to ServerRebootTimeout before. Now I'm going to pull all of the engine-config settings and make sure there aren't others I should tweak. Thank you for the insight. It is very appreciated.
